package servlets;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.google.gson.Gson;

@WebServlet("/PlaatsServlet")
public class PlaatsServlet extends HttpServlet {
  private static final String APPLICATION_JSON = "application/json";
  private static final long serialVersionUID = 1L;
  private static final String[] steden = { "'s Gravenmoer", "'s-Graveland",
      "'s-Gravendeel", "'s-Gravenhage", "'s-Gravenpolder", "'s-Gravenzande",
      "'s-Heer Abtskerke", "'s-Heer Arendskerke", "'s-Heer Hendrikskinderen",
      "'s-Heerenberg", "'s-Heerenbroek", "'s-Heerenhoek", "'s-Hertogenbosch",
      "'t Goy", "'t Haantje", "'t Harde", "'t Loo Oldebroek", "'t Veld",
      "'t Waar", "'t Zand Nh", "'t Zandt Gn", "Aadorp", "Aagtekerke", "Aalden",
      "Aalsmeer", "Aalsmeerderbrug", "Aalst Gld", "Aalten", "Aalzum",
      "Aardenburg", "Aarlanderveen", "Aarle Rixtel", "Aartswoud", "Abbega",
      "Abbekerk", "Abbenbroek", "Abbenes", "Abcoude", "Achlum", "Achterveld",
      "Achthuizen", "Achtmaal", "Acquoy", "Adorp", "Aduard", "Aerdenhout",
      "Aerdt", "Afferden Gld", "Afferden Lb", "Agelo", "Akersloot", "Akkrum",
      "Akmarijp", "Albergen", "Alblasserdam", "Aldeboarn", "Aldtsjerk", "Alem",
      "Alkmaar", "Allingawier", "Almelo", "Almen", "Almere", "Almkerk",
      "Alphen Aan Den Rijn", "Alphen Gld", "Alphen Nb",
      "Alteveer Gem De Wolden", "Alteveer Gem Hoogeveen",
      "Alteveer Gem Noordenveld", "Alteveer Gn", "Altforst", "Ambt Delden",
      "Ameide", "Amen", "America", "Amerongen", "Amersfoort", "Ammerstol",
      "Ammerzoden", "Amstelhoek", "Amstelveen", "Amstenrade", "Amsterdam",
      "Amsterdam Zuidoost", "Andel", "Andelst", "Anderen", "Andijk", "Ane",
      "Anerveen", "Anevelde", "Angeren", "Angerlo", "Anjum", "Ankeveen",
      "Anloo", "Anna Paulowna", "Annen", "Annerveensche Kanaal", "Ansen",
      "Apeldoorn", "Appelscha", "Appeltern", "Appingedam", "Arcen", "Arkel",
      "Arnemuiden", "Arnhem", "Arrien", "Arum", "Asch", "Asperen", "Assen",
      "Assendelft", "Asten", "Augsbuurt", "Augustinusga", "Austerlitz",
      "Avenhorn", "Axel", "Azewijn", "Baaium", "Baak", "Baambrugge", "Baard",
      "Baarland", "Baarle Nassau", "Baarlo Lb", "Baarlo Ov", "Baarn", "Baars",
      "Babberich", "Babylonienbroek", "Badhoevedorp", "Baexem", "Baflo",
      "Bakel", "Bakhuizen", "Bakkeveen", "Balgoij", "Balinge", "Balk",
      "Balkbrug", "Balloerveld", "Balloo", "Ballum", "Baneheide", "Banholt",
      "Bant", "Bantega", "Barchem", "Barendrecht", "Barger Compascuum",
      "Barneveld", "Barsingerhorn", "Basse", "Batenburg", "Bathmen", "Bavel",
      "Bavel Ac", "Bears Fr", "Bedum", "Beegden", "Beek En Donk",
      "Beek Gem Montferland", "Beek Lb", "Beek Ubbergen", "Beekbergen",
      "Beemte Broekland", "Beers Nb", "Beerta", "Beerze", "Beerzerveld",
      "Beesd", "Beesel", "Beetgum", "Beetgumermolen", "Beets Nh",
      "Beetsterzwaag", "Beilen", "Beinsdorp", "Belfeld", "Bellingwolde",
      "Belt Schutsloot", "Beltrum", "Bemelen", "Bemmel", "Beneden Leeuwen",
      "Bennebroek", "Bennekom", "Benneveld", "Benningbroek", "Benschop",
      "Bentelo", "Benthuizen", "Bentveld", "Berg En Dal", "Berg En Terblijt",
      "Bergambacht", "Bergeijk", "Bergen Aan Zee", "Bergen Lb", "Bergen Nh",
      "Bergen Op Zoom", "Bergentheim", "Bergharen", "Berghem", "Bergschenhoek",
      "Beringe", "Berkel En Rodenrijs", "Berkel-Enschot", "Berkenwoude",
      "Berkhout", "Berlicum Nb", "Berlikum Fr", "Bern", "Best", "Beugen",
      "Beuningen Gld", "Beuningen Ov", "Beusichem", "Beutenaken", "Beverwijk",
      "Biddinghuizen", "Bierum", "Biervliet", "Biest Houtakker",
      "Biezenmortel", "Biggekerke", "Bilthoven", "Bingelrade", "Bladel",
      "Blankenham", "Blaricum", "Blauwestad", "Blauwhuis", "Bleiswijk",
      "Blesdijke", "Bleskensgraaf Ca", "Blessum", "Blije", "Blijham",
      "Blitterswijck", "Bloemendaal", "Blokker", "Blokzijl", "Boazum",
      "Bocholtz", "Bodegraven", "Boekel", "Boelenslaan", "Boer", "Boerakker",
      "Boerakker Gem Leek", "Boesingheliede", "Boijl", "Boksum", "Bolsward",
      "Bontebok", "Boornbergum", "Boornzwaag", "Borculo", "Borger",
      "Borgercompagnie", "Borgsweer", "Born", "Borne", "Bornerbroek",
      "Bornwird", "Borssele", "Bosch En Duin", "Boschoord", "Boskoop",
      "Bosschenhoofd", "Botlek Rotterdam", "Bourtange", "Boven Leeuwen",
      "Bovenkarspel", "Bovensmilde", "Boxmeer", "Boxtel", "Braamt", "Brakel",
      "Brandwijk", "Brantgum", "Breda", "Bredevoort", "Breedenbroek",
      "Breezand", "Breezanddijk", "Breskens", "Breugel", "Breukelen Ut",
      "Breukeleveen", "Brielle", "Briltil", "Britsum", "Britswert", "Broek Fr",
      "Broek In Waterland", "Broek Op Langedijk", "Broekhuizen Dr",
      "Broekhuizen Lb", "Broekhuizenvorst", "Broekland Ov", "Broeksterwoude",
      "Bronkhorst", "Bronneger", "Bronnegerveen", "Brouwershaven", "Bruchem",
      "Brucht", "Bruchterveld", "Bruinehaar", "Bruinisse", "Brummen",
      "Brunssum", "Bruntinge", "Buchten", "Budel", "Budel Dorplein",
      "Budel-Schoot", "Buggenum", "Buinen", "Buinerveen", "Buitenkaag",
      "Buitenpost", "Bunde", "Bunne", "Bunnik", "Bunschoten Spakenburg",
      "Burdaard", "Buren Fr", "Buren Gld", "Burgerbrug", "Burgerveen",
      "Burgh Haamstede", "Burgum", "Burgwerd", "Burum", "Bussum", "Buurmalsen",
      "Cadier En Keer", "Cadzand", "Callantsoog", "Capelle Aan Den Ijssel",
      "Castelre", "Castenray", "Casteren", "Castricum", "Chaam", "Clinge",
      "Coevorden", "Colijnsplaat", "Collendoorn", "Colmschate", "Cornjum",
      "Cornwerd", "Cothen", "Creil", "Cromvoirt", "Cruquius", "Cuijk",
      "Culemborg", "Daarle", "Daarlerveen", "Dalem", "Dalen", "Dalerpeel",
      "Dalerveen", "Dalfsen", "Dalmsholte", "Damwoude", "Darp", "De Bilt",
      "De Blesse", "De Bult", "De Cocksdorp", "De Glind", "De Goorn",
      "De Groeve", "De Heen", "De Heurne", "De Hoef", "De Hoeve", "De Kiel",
      "De Klomp", "De Knipe", "De Koog", "De Krim", "De Kwakel", "De Lier",
      "De Lutte", "De Meern", "De Moer", "De Mortel", "De Pol", "De Punt",
      "De Rijp", "De Rips", "De Schiphorst", "De Steeg", "De Tike", "De Valom",
      "De Veenhoop", "De Waal", "De Weere", "De Wijk", "De Wilgen",
      "De Wilp Gn", "De Woude", "De Zilk", "Dearsum", "Dedemsvaart", "Dedgum",
      "Deelen", "Deest", "Deil", "Deinum", "Delden", "Delfgauw",
      "Delfstrahuizen", "Delft", "Delfzijl", "Delwijnen", "Den Andel",
      "Den Bommel", "Den Burg", "Den Dolder", "Den Dungen", "Den Ham Gn",
      "Den Ham Ov", "Den Helder", "Den Hoorn Texel", "Den Hoorn Zh",
      "Den Horn", "Den Hout Nb", "Den Ilp", "Den Oever", "Den Velde",
      "Denekamp", "Deurne", "Deurningen", "Deurze", "Deventer", "Didam",
      "Diemen", "Diepenheim", "Diepenveen", "Dieren", "Diessen", "Diever",
      "Dieverbrug", "Diffelen", "Dijken", "Dinteloord", "Dinxperlo",
      "Diphoorn", "Dirkshorn", "Dirksland", "Dodewaard", "Doenrade",
      "Doesburg", "Doetinchem", "Doezum", "Dokkum", "Doldersum", "Domburg",
      "Donderen", "Dongen", "Dongjum", "Doniaga", "Donkerbroek", "Doorn",
      "Doornenburg", "Doornspijk", "Doorwerth", "Dordrecht", "Dorst",
      "Drachten", "Drachtstercompagnie", "Dreischor", "Drempt", "Dreumel",
      "Driebergen-Rijsenburg", "Drieborg", "Driebruggen", "Driehuis Nh",
      "Driehuizen", "Driel", "Driesum", "Driewegen", "Drijber", "Drimmelen",
      "Drogeham", "Drogteropslagen", "Drongelen", "Dronrijp", "Dronten",
      "Drouwen", "Drouwenermond", "Drouwenerveen", "Drunen", "Druten",
      "Duiven", "Duivendrecht", "Duizel", "Dussen", "Dwingeloo", "Eagum",
      "Earnewald", "Easterein", "Easterlittens", "Eastermar", "Easterwierrum",
      "Echt", "Echteld", "Echten Dr", "Echten Fr", "Echtenerbrug",
      "Eck En Wiel", "Eckelrade", "Edam", "Ede Gld", "Ederveen", "Ee",
      "Eede Zld", "Eefde", "Eelde", "Eelderwolde", "Eemdijk", "Eemnes",
      "Eemshaven", "Een", "Een West", "Eenrum", "Eenum", "Eerbeek", "Eersel",
      "Eerste Exloermond", "Ees", "Eesergroen", "Eeserveen", "Eesterga",
      "Eesveen", "Eethen", "Eext", "Eexterveen", "Eexterveensche Kanaal",
      "Eexterzandvoort", "Egchel", "Egmond Aan Den Hoef", "Egmond Aan Zee",
      "Egmond-Binnen", "Eibergen", "Eijsden", "Eindhoven", "Einighausen",
      "Ekehaar", "Elahuizen", "Elburg", "Eldersloo", "Eleveld", "Elim",
      "Elkenrade", "Ell", "Ellecom", "Ellemeet", "Ellertshaar",
      "Ellewoutsdijk", "Elp", "Elsendorp", "Elshout", "Elsloo Fr", "Elsloo Lb",
      "Elspeet", "Elst Gld", "Elst Ut", "Emmeloord", "Emmen",
      "Emmer Compascuum", "Empe", "Emst", "Engelum", "Engwierum", "Enkhuizen",
      "Ens", "Enschede", "Enspijk", "Enter", "Enumatil", "Epe", "Epen",
      "Eppenhuizen", "Epse", "Erica", "Erichem", "Erlecom", "Erm", "Ermelo",
      "Erp", "Esbeek", "Esch", "Escharen", "Espel", "Est", "Etten Gld",
      "Etten-Leur", "Europoort Rotterdam", "Eursinge",
      "Eursinge Gem De Wolden", "Everdingen", "Evertsoord", "Ewijk",
      "Exloerveen", "Exloo", "Exmorra", "Eygelshoven", "Eys", "Ezinge",
      "Farmsum", "Feerwerd", "Ferwert", "Ferwoude", "Fijnaart", "Finkum",
      "Finsterwolde", "Firdgum", "Fleringen", "Fluitenberg", "Fochteloo",
      "Follega", "Folsgare", "Foudgum", "Foxhol", "Foxwolde", "Franeker",
      "Frederiksoord", "Friens", "Frieschepalen", "Froombosch", "Gaanderen",
      "Gaast", "Gaastmeer", "Galder", "Gameren", "Gapinge", "Garderen",
      "Garmerwolde", "Garminge", "Garnwerd", "Garrelsweer", "Garsthuizen",
      "Garyp", "Gassel", "Gasselte", "Gasselternijveen",
      "Gasselternijveenschemond", "Gastel", "Gasteren", "Gauw", "Geelbroek",
      "Geersdijk", "Geertruidenberg", "Geervliet", "Gees", "Geesbrug",
      "Geesteren Gld", "Geesteren Ov", "Geeuwenbrug", "Geffen", "Geijsteren",
      "Geldermalsen", "Gelderswoude", "Geldrop", "Geleen", "Gellicum",
      "Gelselaar", "Gemert", "Gemonde", "Genderen", "Gendringen", "Gendt",
      "Genemuiden", "Gennep", "Gerkesklooster", "Gersloot", "Geulle",
      "Giesbeek", "Giessen", "Giessenburg", "Gieten", "Gieterveen", "Giethmen",
      "Giethoorn", "Gilze", "Ginnum", "Glane", "Glimmen", "Godlinze",
      "Goedereede", "Goenga", "Goengahuizen", "Goes", "Goingarijp", "Goirle",
      "Goor", "Gorinchem", "Gorredijk", "Gorssel", "Gouda", "Gouderak",
      "Goudriaan", "Goudswaard", "Goutum", "Graauw", "Grafhorst", "Graft",
      "Gramsbergen", "Grashoek", "Grathem", "Grave", "Greonterp",
      "Grevenbicht", "Griendtsveen", "Grijpskerk", "Grijpskerke", "Groede",
      "Groenekan", "Groeningen", "Groenlo", "Groesbeek", "Groessen", "Groet",
      "Grolloo", "Groningen", "Gronsveld", "Groot Ammers", "Grootebroek",
      "Grootegast", "Grootschermer", "Grou", "Grubbenvorst", "Gulpen",
      "Guttecoven", "Gytsjerk", "Haaften", "Haaksbergen", "Haalderen",
      "Haaren", "Haarle Gem Hellendoorn", "Haarle Gem Tubbergen", "Haarlem",
      "Haarlemmerliede", "Haarlo", "Haarsteeg", "Haarzuilens", "Haastrecht",
      "Haelen", "Hagestein", "Haghorst", "Haler", "Halfweg Nh", "Hall",
      "Halle", "Hallum", "Halsteren", "Handel", "Hank", "Hansweert", "Hantum",
      "Hantumeruitburen", "Hantumhuizen", "Hapert", "Haps", "Harbrinkhoek",
      "Hardenberg", "Harderwijk", "Hardinxveld Giessendam", "Haren Gn",
      "Haren Nb", "Harfsen", "Harich", "Haringhuizen", "Harkema", "Harkstede",
      "Harlingen", "Harmelen", "Harreveld", "Harskamp", "Hartwerd",
      "Haskerdijken", "Haskerhorne", "Hasselt", "Hattem", "Hattemerbroek",
      "Haule", "Haulerwijk", "Hauwert", "Havelte", "Havelterberg",
      "Hazerswoude Dorp", "Hazerswoude Rijndijk", "Hedel", "Heeg", "Heel",
      "Heelsum", "Heelweg", "Heemserveen", "Heemskerk", "Heemstede",
      "Heenvliet", "Heerde", "Heerenveen", "Heerewaarden", "Heerhugowaard",
      "Heerjansdam", "Heerle", "Heerlen", "Heesch", "Heesselt",
      "Heeswijk Dinther", "Heeten", "Heeze", "Hegebeintum", "Hegelsom",
      "Hei En Boeicop", "Heibloem", "Heide", "Heijen", "Heijenrath",
      "Heijningen", "Heikant", "Heilig Landstichting", "Heiligerlee", "Heiloo",
      "Heinenoord", "Heinkenszand", "Heino", "Hekelingen", "Hekendorp",
      "Helden", "Helenaveen", "Hellendoorn", "Hellevoetsluis", "Hellouw",
      "Hellum", "Helmond", "Helvoirt", "Hem", "Hemelum", "Hemmen", "Hempens",
      "Hemrik", "Hendrik Ido Ambacht", "Hengelo Gld", "Hengelo Ov",
      "Hengevelde", "Hengstdijk", "Hensbroek", "Herbaijum", "Herkenbosch",
      "Herkingen", "Hernen", "Herpen", "Herten", "Hertme", "Herveld", "Herwen",
      "Herwijnen", "Heteren", "Heukelom Nb", "Heukelum", "Heumen", "Heurne",
      "Heusden Gem Asten", "Heusden Gem Heusden", "Heythuysen", "Hezingen",
      "Hiaure", "Hichtum", "Hidaard", "Hierden", "Hieslum", "Hijken", "Hijum",
      "Hilaard", "Hillegom", "Hilvarenbeek", "Hilversum", "Hindeloopen",
      "Hinnaard", "Hippolytushoef", "Hitzum", "Hobrede", "Hoedekenskerke",
      "Hoek", "Hoek Van Holland", "Hoenderloo", "Hoensbroek", "Hoenzadriel",
      "Hoevelaken", "Hoeven", "Hoge Hexel", "Hollandsche Rading",
      "Hollandscheveld", "Hollum", "Holsloot", "Holten", "Holthees",
      "Holtheme", "Holthone", "Holtum", "Holwerd", "Holwierde", "Hommerts",
      "Homoet", "Honselersdijk", "Hoofddorp", "Hoofdplaat", "Hoog Keppel",
      "Hoog Soeren", "Hoogblokland", "Hooge Mierde", "Hooge Zwaluwe",
      "Hoogeloon", "Hoogenweg", "Hoogerheide", "Hoogersmilde", "Hoogeveen",
      "Hoogezand", "Hooghalen", "Hoogkarspel", "Hoogland", "Hooglanderveen",
      "Hoogmade", "Hoogvliet Rotterdam", "Hoogwoud", "Hoorn Nh", "Hoornaar",
      "Hoornsterzwaag", "Horn", "Hornhuizen", "Horssen", "Horst", "Houten",
      "Houtigehage", "Houwerzijl", "Huijbergen", "Huis Ter Heide Dr",
      "Huis Ter Heide Ut", "Huissen", "Huizen", "Huizinge", "Hulsberg",
      "Hulsel", "Hulshorst", "Hulst", "Hulten", "Hummelo", "Huns", "Hunsel",
      "Hurdegaryp", "Hurwenen", "Idaerd", "Idsegahuizum", "Idskenhuizen",
      "Idzega", "Iens", "Ijhorst", "Ijlst", "Ijmuiden", "Ijsselham",
      "Ijsselmuiden", "Ijsselstein Ut", "Ijzendijke", "Ijzendoorn", "Ilpendam",
      "Indijk", "Ingber", "Ingen", "It Heidenskip", "Itens", "Ittervoort",
      "Jaarsveld", "Jabeek", "Jannum", "Jellum", "Jelsum", "Jirnsum", "Jislum",
      "Jisp", "Jistrum", "Jonkerslan", "Jonkersvaart", "Joppe", "Jorwert",
      "Joure", "Jouswier", "Jubbega", "Jutrijp", "Kaag", "Kaatsheuvel",
      "Kalenberg", "Kallenkote", "Kamerik", "Kampen", "Kamperland",
      "Kamperveen", "Kantens", "Kapel Avezaath", "Kapel Avezaath Buren",
      "Kapelle", "Kapellebrug", "Katlijk", "Kats", "Kattendijke", "Katwijk Nb",
      "Katwijk Zh", "Katwoude", "Kedichem", "Keijenborg", "Kekerdom",
      "Kelpen-Oler", "Kerk Avezaath", "Kerk Avezaath Tiel", "Kerkdriel",
      "Kerkenveld", "Kerkrade", "Kerkwerve", "Kerkwijk", "Kessel Lb",
      "Kesteren", "Kiel-Windeweer", "Kilder", "Kimswerd", "Kinderdijk",
      "Klaaswaal", "Klarenbeek", "Klazienaveen", "Klijndijk", "Klimmen",
      "Kloetinge", "Klooster Lidlum", "Kloosterburen", "Kloosterhaar",
      "Kloosterzande", "Klundert", "Knegsel", "Kockengen", "Koedijk",
      "Koekange", "Koewacht", "Kolderwolde", "Kolham", "Kolhorn", "Kollum",
      "Kollumerpomp", "Kollumerzwaag", "Kommerzijl", "Koningsbosch",
      "Koningslust", "Koog Aan De Zaan", "Kootstertille", "Kootwijk",
      "Kootwijkerbroek", "Kornhorn", "Kornwerderzand", "Kortehemmen",
      "Kortenhoef", "Kortgene", "Koudekerk Aan Den Rijn", "Koudekerke",
      "Koudum", "Koufurderrige", "Krabbendijke", "Kraggenburg", "Kreileroord",
      "Krewerd", "Krimpen Aan De Lek", "Krimpen Aan Den Ijssel",
      "Kring Van Dorth", "Krommenie", "Kronenberg", "Kropswolde", "Kruiningen",
      "Kruisland", "Kubaard", "Kudelstaart", "Kuinre", "Kuitaart",
      "Kwadendamme", "Kwadijk", "Kwintsheul", "Laag Keppel", "Laag Soeren",
      "Laag Zuthem", "Lage Mierde", "Lage Vuursche", "Lage Zwaluwe",
      "Lageland", "Lambertschaag", "Lamswaarde", "Landgraaf", "Landhorst",
      "Landsmeer", "Langbroek", "Langedijke", "Langelille", "Langelo Dr",
      "Langenboom", "Langerak Zh", "Langeveen", "Langeweg", "Langezwaag",
      "Langweer", "Laren Gld", "Laren Nh", "Lathum", "Lattrop Breklenkamp",
      "Lauwersoog", "Lauwerzijl", "Ledeacker", "Leek", "Leende", "Leens",
      "Leerbroek", "Leerdam", "Leermens", "Leersum", "Leeuwarden", "Legemeer",
      "Leiden", "Leiderdorp", "Leidschendam", "Leimuiden", "Leimuiderbrug",
      "Lekkerkerk", "Lekkum", "Lellens", "Lelystad", "Lemele", "Lemelerveld",
      "Lemiers", "Lemmer", "Lengel", "Lent", "Leons", "Lepelstraat",
      "Lettelbert", "Lettele", "Leunen", "Leur", "Leusden", "Leuth",
      "Leutingewolde", "Leuvenheim", "Leveroy", "Lewedorp", "Lexmond",
      "Lichtaard", "Lichtenvoorde", "Liempde", "Lienden", "Lierderholthuis",
      "Lieren", "Lierop", "Lieshout", "Liessel", "Lievelde", "Lieveren",
      "Lijnden", "Limbricht", "Limmen", "Linde Dr", "Linden", "Linne",
      "Linschoten", "Lioessens", "Lippenhuizen", "Lisse", "Lisserbroek",
      "Lith", "Lithoijen", "Lobith", "Lochem", "Loenen Aan De Vecht",
      "Loenen Gld", "Loenersloot", "Loenga", "Loerbeek", "Lollum", "Lomm",
      "Longerhouw", "Loo Gld", "Loon", "Loon Op Zand", "Loosbroek",
      "Loosdrecht", "Loozen", "Lopik", "Lopikerkapel", "Loppersum", "Losdorp",
      "Losser", "Lottum", "Lucaswolde", "Luchthaven Schiphol", "Luddeweer",
      "Luinjeberd", "Lunteren", "Lutjebroek", "Lutjegast", "Lutjewinkel",
      "Luttelgeest", "Lutten", "Luttenberg", "Luxwoude", "Luyksgestel",
      "Lytsewierrum", "Maarheeze", "Maarn", "Maarsbergen", "Maarssen",
      "Maartensdijk", "Maasbommel", "Maasbracht", "Maasbree", "Maasdam",
      "Maasdijk", "Maashees", "Maasland", "Maassluis", "Maastricht",
      "Maastricht-Airport", "Maasvlakte Rotterdam", "Macharen", "Made",
      "Makkinga", "Makkum Fr", "Malden", "Mander", "Manderveen", "Mantgum",
      "Mantinge", "Maren Kessel", "Margraten", "Maria Hoop", "Mariahout",
      "Mariaparochie", "Marienberg", "Marienheem", "Marienvelde",
      "Marijenkampen", "Markelo", "Marken", "Markenbinnen", "Marknesse",
      "Marle", "Marrum", "Marssum", "Marum", "Marwijksoord", "Mastenbroek",
      "Matsloot", "Maurik", "Mechelen", "Medemblik", "Meeden", "Meedhuizen",
      "Meerkerk", "Meerlo", "Meerssen", "Meeuwen", "Megchelen", "Megen",
      "Meijel", "Melderslo", "Melick", "Meliskerke", "Melissant", "Menaldum",
      "Mensingeweer", "Meppel", "Meppen", "Merkelbeek", "Merselo", "Meteren",
      "Meterik", "Metslawier", "Mheer", "Middelaar", "Middelburg",
      "Middelharnis", "Middelie", "Middelstum", "Middenbeemster", "Middenmeer",
      "Midlaren", "Midlum", "Midwolda", "Midwolde", "Midwoud", "Miedum",
      "Mierlo", "Mijdrecht", "Mijnsheerenland", "Mildam", "Milheeze", "Mill",
      "Millingen Aan De Rijn", "Milsbeek", "Minnertsga", "Mirns", "Moddergat",
      "Moerdijk", "Moergestel", "Moerkapelle", "Moerstraten", "Molenaarsgraaf",
      "Molenhoek Lb", "Molenschot", "Molkwerum", "Monnickendam", "Monster",
      "Montfoort", "Montfort", "Mook", "Mookhoek", "Moordrecht", "Moorveld",
      "Morra", "Muiden", "Muiderberg", "Munein", "Munnekeburen", "Munnekezijl",
      "Munstergeleen", "Muntendam", "Mussel", "Musselkanaal", "Naaldwijk",
      "Naarden", "Nagele", "Nederasselt", "Nederhemert", "Nederhorst Den Berg",
      "Nederland", "Nederweert", "Nederweert Eind", "Neede", "Neer",
      "Neerijnen", "Neeritter", "Neerkant", "Nes Ameland",
      "Nes Gem Boarnsterhim", "Nes Gem Dongeradeel", "Netersel", "Netterden",
      "Niawier", "Nibbixwoud", "Niebert", "Niehove", "Niekerk De Marne",
      "Niekerk Grootegast", "Nietap", "Nieuw Amsterdam", "Nieuw Annerveen",
      "Nieuw Balinge", "Nieuw Beerta", "Nieuw Beijerland", "Nieuw Buinen",
      "Nieuw Dordrecht", "Nieuw Heeten", "Nieuw Lekkerland", "Nieuw Namen",
      "Nieuw Roden", "Nieuw Scheemda", "Nieuw Schoonebeek", "Nieuw Vennep",
      "Nieuw Vossemeer", "Nieuw Weerdinge", "Nieuw- En Sint Joosland",
      "Nieuwaal", "Nieuwdorp Zld", "Nieuwe Niedorp", "Nieuwe Pekela",
      "Nieuwe Tonge", "Nieuwe Wetering", "Nieuwebrug", "Nieuwediep",
      "Nieuwegein", "Nieuwehorne", "Nieuwendijk Nb", "Nieuwer Ter Aa",
      "Nieuwerbrug", "Nieuwerkerk", "Nieuwerkerk Ad Ijssel", "Nieuweroord",
      "Nieuwersluis", "Nieuweschans", "Nieuweschoot", "Nieuwkoop",
      "Nieuwkuijk", "Nieuwland", "Nieuwlande", "Nieuwlande Coevorden",
      "Nieuwleusen", "Nieuwolda", "Nieuwpoort", "Nieuwstadt", "Nieuwveen",
      "Nieuwvliet", "Niezijl", "Niftrik", "Nigtevecht", "Nij Beets",
      "Nijbroek", "Nijeberkoop", "Nijega", "Nijehaske", "Nijeholtpade",
      "Nijeholtwolde", "Nijelamer", "Nijemirdum", "Nijensleek", "Nijetrijne",
      "Nijeveen", "Nijhuizum", "Nijkerk Gld", "Nijkerkerveen", "Nijland",
      "Nijlande", "Nijmegen", "Nijverdal", "Nispen", "Nisse", "Nistelrode",
      "Noardburgum", "Nooitgedacht", "Noorbeek", "Noord Sleen",
      "Noord-Scharwoude", "Noordbeemster", "Noordbroek", "Noordeinde Gld",
      "Noordeinde Nh", "Noordeloos", "Noorden", "Noordgouwe", "Noordhoek",
      "Noordhorn", "Noordlaren", "Noordscheschut", "Noordwelle",
      "Noordwijk Gn", "Noordwijk Zh", "Noordwijkerhout", "Noordwolde Fr",
      "Noordwolde Gn", "Nootdorp", "Norg", "Notter", "Nuenen", "Nuis",
      "Nuland", "Numansdorp", "Nunhem", "Nunspeet", "Nuth", "Nutter",
      "Obbicht", "Obdam", "Ochten", "Odijk", "Odiliapeel", "Odoorn",
      "Odoornerveen", "Oeffelt", "Oegstgeest", "Oene", "Oentsjerk",
      "Offingawier", "Ohe En Laak", "Oijen", "Oirlo", "Oirsbeek", "Oirschot",
      "Oisterwijk", "Okkenbroek", "Olburgen", "Oldeberkoop", "Oldebroek",
      "Oldeholtpade", "Oldeholtwolde", "Oldehove", "Oldekerk", "Oldelamer",
      "Oldemarkt", "Oldenzaal", "Oldenzijl", "Oldeouwer", "Oldetrijne", "Olst",
      "Olterterp", "Ommel", "Ommen", "Ommeren", "Onderdendam", "Onna", "Onnen",
      "Onstwedde", "Ooij", "Ooltgensplaat", "Oost Graftdijk",
      "Oost West En Middelbeers", "Oost-Souburg", "Oostburg", "Oostdijk",
      "Oosteind", "Oosterbeek", "Oosterbierum", "Oosterblokker",
      "Oosterend Nh", "Oosterhesselen", "Oosterhout Gem Nijmegen",
      "Oosterhout Gld", "Oosterhout Nb", "Oosterland", "Oosterleek",
      "Oosternieland", "Oosternijkerk", "Oosterstreek", "Oosterwijk",
      "Oosterwijtwerd", "Oosterwolde Fr", "Oosterwolde Gld", "Oosterzee",
      "Oosthem", "Oosthuizen", "Oostkapelle", "Oostknollendam", "Oostrum Fr",
      "Oostrum Lb", "Oostvoorne", "Oostwold Gem Leek", "Oostwold Scheemda",
      "Oostwoud", "Oostzaan", "Ootmarsum", "Opeinde", "Opende", "Ophemert",
      "Opheusden", "Opijnen", "Oploo", "Opmeer", "Oppenhuizen", "Opperdoes",
      "Oranje", "Oranjewoud", "Orvelte", "Ospel", "Oss", "Ossendrecht",
      "Ossenisse", "Ossenwaard Ut", "Ossenzijl", "Oterleek", "Otterlo",
      "Ottersum", "Ottoland", "Oud Ade", "Oud Alblas", "Oud Annerveen",
      "Oud Beijerland", "Oud Gastel", "Oud Ootmarsum", "Oud Vossemeer",
      "Oud Zuilen", "Ouddorp Zh", "Oude Bildtzijl", "Oude Leije", "Oude Meer",
      "Oude Niedorp", "Oude Pekela", "Oude Wetering", "Oude Willem",
      "Oude-Tonge", "Oudega Gaast Sleat", "Oudega Gem Smallingerlnd",
      "Oudega Gem Wymbritserad", "Oudehaske", "Oudehorne", "Oudelande",
      "Oudemirdum", "Oudemolen Dr", "Oudemolen Nb", "Oudenbosch",
      "Oudendijk Nh", "Oudenhoorn", "Ouderkerk Aan De Amstel",
      "Ouderkerk Aan Den Ijssel", "Oudeschans", "Oudeschild", "Oudeschip",
      "Oudeschoot", "Oudesluis", "Oudewater", "Oudezijl", "Oudkarspel",
      "Oudorp Nh", "Oudwoude", "Ouwerkerk", "Ouwster Nijega", "Ouwsterhaule",
      "Overasselt", "Overberg", "Overdinkel", "Overloon", "Overschild",
      "Overslag", "Overveen", "Ovezande", "Paasloo", "Paesens", "Pannerden",
      "Panningen", "Papekop", "Papendrecht", "Papenhoven", "Papenvoort",
      "Parrega", "Paterswolde", "Peest", "Peins", "Peize", "Peperga",
      "Pernis Rotterdam", "Persingen", "Pesse", "Petten", "Philippine",
      "Piaam", "Piershil", "Pieterburen", "Pietersbierum", "Pieterzijl",
      "Pijnacker", "Pingjum", "Plasmolen", "Poederoijen", "Poeldijk",
      "Polsbroek", "Poortugaal", "Poortvliet", "Poppenwier", "Posterholt",
      "Prinsenbeek", "Puiflijk", "Punthorst", "Purmer", "Purmerend",
      "Purmerland", "Puth", "Putte", "Putten", "Puttershoek", "Raalte",
      "Raamsdonk", "Raamsdonksveer", "Raard", "Radewijk", "Radio Kootwijk",
      "Raerd", "Randwijk", "Ransdaal", "Rasquert", "Ravenstein", "Ravenswaaij",
      "Ravenswoud", "Reahus", "Reduzum", "Reek", "Reeuwijk", "Reijmerstok",
      "Reitsum", "Rekken", "Renesse", "Renkum", "Renswoude", "Ressen",
      "Ressen Gem Nijmegen", "Retranchement", "Reusel", "Reutum", "Reuver",
      "Rha", "Rheden", "Rhee", "Rheeze", "Rheezerveen", "Rhenen", "Rhenoy",
      "Rhoon", "Ridderkerk", "Ried", "Riel", "Rien", "Riethoven", "Rietmolen",
      "Rijen", "Rijkevoort", "Rijnsaterwoude", "Rijnsburg", "Rijpwetering",
      "Rijs", "Rijsbergen", "Rijsenhout", "Rijssen", "Rijswijk Gld",
      "Rijswijk Nb", "Rijswijk Zh", "Rilland", "Rinsumageest", "Ritthem",
      "Rockanje", "Roden", "Roderesch", "Roderwolde", "Roelofarendsveen",
      "Roermond", "Rogat", "Roggel", "Rohel", "Rolde", "Roodeschool",
      "Roodkerk", "Roosendaal", "Roosteren", "Rosmalen", "Rossum Gld",
      "Rossum Ov", "Roswinkel", "Rotstergaast", "Rotsterhaule", "Rotterdam",
      "Rotterdam Albrands", "Rottevalle", "Rottum Fr", "Rottum Gn", "Rouveen",
      "Rozenburg Nh", "Rozenburg Zh", "Rozendaal", "Rucphen", "Ruigahuizen",
      "Ruinen", "Ruinerwold", "Rumpt", "Rutten", "Ruurlo",
      "Rykevoort-De Walsert", "Ryptsjerk", "Saaksum", "Saasveld",
      "Saaxumhuizen", "Sambeek", "Sandfirden", "Santpoort-Noord",
      "Santpoort-Zuid", "Sappemeer", "Sas Van Gent", "Sassenheim", "Sauwerd",
      "Schagen", "Schagerbrug", "Schaijk", "Schalkhaar", "Schalkwijk",
      "Schalsum", "Schardam", "Scharendijke", "Scharmer", "Scharnegoutum",
      "Scharsterbrug", "Scharwoude", "Scheemda", "Scheerwolde",
      "Schellinkhout", "Schelluinen", "Schermerhorn", "Scherpenisse",
      "Scherpenzeel Fr", "Scherpenzeel Gld", "Schettens", "Scheulder",
      "Schiedam", "Schiermonnikoog", "Schijf", "Schijndel", "Schildwolde",
      "Schimmert", "Schin Op Geul", "Schingen", "Schinnen", "Schinveld",
      "Schipborg", "Schiphol", "Schiphol-Rijk", "Schipluiden", "Schoondijke",
      "Schoonebeek", "Schoonhoven", "Schoonloo", "Schoonoord", "Schoonrewoerd",
      "Schoorl", "Schore", "Schouwerzijl", "Schraard", "Schuinesloot",
      "Sebaldeburen", "Sellingen", "Serooskerke Schouwen",
      "Serooskerke Walcheren", "Sevenum", "Sexbierum", "Sibculo",
      "Sibrandabuorren", "Siddeburen", "Siebengewald", "Siegerswoude",
      "Sijbekarspel", "Sijbrandahuis", "Silvolde", "Simonshaven", "Simpelveld",
      "Sinderen", "Sint Agatha", "Sint Annaland", "Sint Annaparochie",
      "Sint Annen", "Sint Anthonis", "Sint Geertruid", "Sint Hubert",
      "Sint Jacobiparochie", "Sint Jansklooster", "Sint Jansteen",
      "Sint Joost", "Sint Kruis", "Sint Maarten", "Sint Maartensbrug",
      "Sint Maartensdijk", "Sint Maartensvlotbrug", "Sint Michielsgestel",
      "Sint Nicolaasga", "Sint Odilienberg", "Sint Oedenrode", "Sint Pancras",
      "Sint Philipsland", "Sint Willebrord", "Sintjohannesga", "Sirjansland",
      "Sittard", "Slagharen", "Slappeterp", "Sleen", "Sleeuwijk", "Slenaken",
      "Sliedrecht", "Slijk Ewijk", "Slijkenburg", "Slochteren", "Slootdorp",
      "Sloten Fr", "Sluis", "Sluiskil", "Smakt", "Smalle Ee", "Smallebrugge",
      "Smilde", "Snakkerburen", "Sneek", "Snelrewaard", "Snikzwaag",
      "Soerendonk", "Soest", "Soesterberg", "Someren", "Sommelsdijk", "Son",
      "Sondel", "Sonnega", "Spaarndam", "Spaarndam West", "Spanbroek",
      "Spanga", "Spankeren", "Spannum", "Spaubeek", "Spier", "Spierdijk",
      "Spijk Gem Lingewaal", "Spijk Gld", "Spijk Gn", "Spijkenisse",
      "Spijkerboor Dr", "Spijkerboor Nh", "Sprang-Capelle", "Sprundel", "Spui",
      "Stad Aan 't Haringvliet", "Stadskanaal", "Stampersgat",
      "Standdaarbuiten", "Staphorst", "Starnmeer", "Startenhuizen",
      "Startenhuizen Lopp", "Stavenisse", "Stavoren", "Stedum",
      "Steenbergen Dr", "Steenbergen Nb", "Steendam", "Steenderen",
      "Steenenkamer", "Steensel", "Steenwijk", "Steenwijkerwold", "Stegeren",
      "Steggerda", "Steijl", "Stein Lb", "Stellendam", "Sterksel",
      "Stevensbeek", "Stevensweert", "Stieltjeskanaal", "Stiens", "Stitswerd",
      "Stokkum", "Stolwijk", "Stompetoren", "Stoutenburg", "Stoutenburg Noord",
      "Stramproy", "Streefkerk", "Strijbeek", "Strijen", "Strijensas", "Stroe",
      "Stroobos", "Stuifzand", "Sumar", "Surhuisterveen", "Surhuizum",
      "Susteren", "Suwald", "Swalmen", "Sweikhuizen", "Swichum", "Swifterbant",
      "Swolgen", "Taarlo", "Teeffelen", "Teerns", "Tegelen", "Ten Boer",
      "Ten Post", "Ter Aar", "Ter Aard", "Ter Apel", "Ter Apelkanaal",
      "Ter Heijde", "Ter Idzard", "Terband", "Terborg", "Terheijden",
      "Terherne", "Terhole", "Terkaple", "Termunten", "Termunterzijl",
      "Ternaard", "Terneuzen", "Teroele", "Terschelling Baaiduinen",
      "Terschelling Formerum", "Terschelling Hee", "Terschelling Hoorn",
      "Terschelling Kaart", "Terschelling Kinnum", "Terschelling Landerum",
      "Terschelling Lies", "Terschelling Midsland", "Terschelling Oosterend",
      "Terschelling Seeryp", "Terschelling West", "Terschuur", "Tersoal",
      "Terwispel", "Terwolde", "Teteringen", "Teuge", "Thesinge", "Tholen",
      "Thorn", "Tiel", "Tiendeveen", "Tienhoven Ut", "Tienhoven Zh", "Tienray",
      "Tijnje", "Tilburg", "Tilligte", "Tinallinge", "Tinte", "Tirns",
      "Tjalhuizum", "Tjalleberd", "Tjerkgaast", "Tjerkwerd", "Tjuchem",
      "Tolbert", "Toldijk", "Tolkamer", "Tollebeek", "Tonden", "Toornwerd",
      "Tricht", "Triemen", "Tripscompagnie", "Tubbergen", "Tuil",
      "Tuitjenhorn", "Tuk", "Tull En 't Waal", "Tweede Exloermond",
      "Tweede Valthermond", "Twello", "Twijzel", "Twijzelerheide", "Twisk",
      "Tynaarlo", "Tytsjerk", "Tzum", "Tzummarum", "Ubbena", "Ubbergen",
      "Uddel", "Uden", "Udenhout", "Uffelte", "Ugchelen", "Uitdam", "Uitgeest",
      "Uithoorn", "Uithuizen", "Uithuizermeeden", "Uitwellingerga", "Uitwijk",
      "Ulestraten", "Ulft", "Ulicoten", "Ulrum", "Ulvenhout", "Ulvenhout Ac",
      "Ureterp", "Urk", "Urmond", "Ursem", "Ursem Gem Schermer", "Usquert",
      "Utrecht", "Vaals", "Vaassen", "Valburg", "Valkenburg Lb",
      "Valkenburg Zh", "Valkenswaard", "Valthe", "Valthermond", "Varik",
      "Varsselder Veldhunten", "Varsseveld", "Vasse", "Veelerveen", "Veen",
      "Veendam", "Veenendaal", "Veenhuizen", "Veeningen", "Veenklooster",
      "Veenoord", "Veenwouden", "Veere", "Veessen", "Vegelinsoord", "Veghel",
      "Velddriel", "Velden", "Veldhoven", "Velp Gld", "Velp Nb",
      "Velsen-Noord", "Velsen-Zuid", "Velserbroek", "Ven-Zelderheide",
      "Venebrugge", "Venhorst", "Venhuizen", "Venlo", "Venray", "Vessem",
      "Vethuizen", "Veulen", "Vianen Nb", "Vianen Ut", "Vierakker",
      "Vierhouten", "Vierhuizen", "Vierlingsbeek", "Vierpolders", "Vijfhuizen",
      "Vijlen", "Vilsteren", "Vinkega", "Vinkel", "Vinkenbuurt", "Vinkeveen",
      "Visvliet", "Vlaardingen", "Vlagtwedde", "Vledder", "Vledderveen Dr",
      "Vledderveen Gn", "Vleuten", "Vlieland", "Vlierden", "Vlijmen",
      "Vlissingen", "Vlist", "Vlodrop", "Voerendaal", "Vogelenzang",
      "Vogelwaarde", "Volendam", "Volkel", "Vollenhove", "Vondelingenplaat Rt",
      "Voorburg", "Voorhout", "Voorschoten", "Voorst Gem Voorst",
      "Voorst Oude Ijsselstreek", "Voorthuizen", "Vorchten", "Vorden",
      "Vorstenbosch", "Vortum Mullem", "Vragender", "Vredenheim", "Vredepeel",
      "Vreeland", "Vries", "Vriescheloo", "Vriezenveen", "Vroomshoop",
      "Vrouwenakker", "Vrouwenparochie", "Vrouwenpolder", "Vught", "Vuren",
      "Waaksens Gem Litt", "Waal", "Waalre", "Waalwijk", "Waarde",
      "Waardenburg", "Waarder", "Waardhuizen", "Waarland",
      "Waaxens Gem Dongeradeel", "Wachtum", "Waddinxveen", "Wadenoijen",
      "Wagenberg", "Wagenborgen", "Wageningen", "Walem", "Walsoorden", "Wamel",
      "Wanneperveen", "Wanroij", "Wanssum", "Wanswert", "Wapenveld", "Wapse",
      "Wapserveen", "Warder", "Warffum", "Warfhuizen", "Warfstermolen",
      "Warmenhuizen", "Warmond", "Warns", "Warnsveld", "Warstiens", "Warten",
      "Waskemeer", "Waspik", "Wassenaar", "Wateren", "Watergang",
      "Waterhuizen", "Wateringen", "Waterlandkerkje", "Waverveen", "Wedde",
      "Weerselo", "Weert", "Weesp", "Wehe Den Hoorn", "Wehl", "Weidum",
      "Weiteveen", "Wekerom", "Well Gld", "Well Lb", "Wellerlooi", "Welsum",
      "Wemeldinge", "Wenum Wiesel", "Wergea", "Werkendam", "Werkhoven",
      "Wernhout", "Wervershoof", "Wesepe", "Wessem", "West Graftdijk",
      "Westbeemster", "Westbroek", "Westdorp", "Westdorpe", "Westendorp",
      "Westerbeek", "Westerbork", "Westerbroek", "Westeremden", "Westergeest",
      "Westerhaar-Vriezenv Wijk", "Westerhoven", "Westerland", "Westerlee Gn",
      "Westernieland", "Westervelde", "Westervoort", "Westerwijtwerd",
      "Westhem", "Westhoek", "Westkapelle", "Westknollendam", "Westmaas",
      "Westwoud", "Westzaan", "Wetering", "Weteringbrug", "Wetsinge",
      "Wetzens", "Weurt", "Wezep", "Wezup", "Wezuperbrug", "Wichmond", "Wier",
      "Wierden", "Wieringerwaard", "Wieringerwerf", "Wierum", "Wijchen",
      "Wijckel", "Wijdenes", "Wijdewormer", "Wijhe", "Wijk Aan Zee",
      "Wijk Bij Duurstede", "Wijk En Aalburg", "Wijlre", "Wijnaldum",
      "Wijnandsrade", "Wijnbergen", "Wijngaarden Zh", "Wijnjewoude", "Wijster",
      "Wilbertoord", "Wildervank", "Wilhelminadorp", "Wilhelminaoord",
      "Willemsoord", "Willemstad Nb", "Wilnis", "Wilp Gld", "Wilsum", "Winde",
      "Windraak", "Winkel", "Winneweer", "Winschoten", "Winssen", "Winsum Fr",
      "Winsum Gn", "Wintelre", "Winterswijk", "Winterswijk Brinkheurne",
      "Winterswijk Corle", "Winterswijk Henxel", "Winterswijk Huppel",
      "Winterswijk Kotten", "Winterswijk Meddo", "Winterswijk Miste",
      "Winterswijk Ratum", "Winterswijk Woold", "Wirdum Fr", "Wirdum Gn",
      "Wissenkerke", "Witharen", "Witmarsum", "Witte Paarden", "Wittelte",
      "Wittem", "Witteveen", "Wiuwert", "Wjelsryp", "Woensdrecht", "Woerden",
      "Woerdense Verlaat", "Wognum", "Woldendorp", "Wolfheze",
      "Wolphaartsdijk", "Wolsum", "Woltersum", "Wolvega", "Wommels", "Wons",
      "Workum", "Wormer", "Wormerveer", "Woubrugge", "Woudbloem", "Woudenberg",
      "Woudrichem", "Woudsend", "Wouterswoude", "Wouw", "Wouwse Plantage",
      "Wyns", "Wytgaard", "Yde", "Yerseke", "Ypecolsga", "Ysbrechtum",
      "Ysselsteyn Lb", "Zaamslag", "Zaandam", "Zaandijk", "Zalk", "Zaltbommel",
      "Zandberg Dr", "Zandeweer", "Zandhuizen", "Zandpol", "Zandvoort",
      "Zeddam", "Zeegse", "Zeeland", "Zeerijp", "Zeewolde", "Zegge", "Zegveld",
      "Zeijen", "Zeijerveen", "Zeijerveld", "Zeist", "Zelhem", "Zenderen",
      "Zennewijnen", "Zetten", "Zevenaar", "Zevenbergen",
      "Zevenbergschen Hoek", "Zevenbergschen Hoek Dri", "Zevenhoven",
      "Zevenhuizen Gn", "Zevenhuizen Zh", "Zierikzee", "Zieuwent",
      "Zijderveld", "Zijdewind", "Zijldijk", "Zoelen", "Zoelmond",
      "Zoetermeer", "Zoeterwoude", "Zonnemaire", "Zorgvlied", "Zoutelande",
      "Zoutkamp", "Zuid-Beijerland", "Zuid-Scharwoude", "Zuidbroek",
      "Zuiddorpe", "Zuidermeer", "Zuiderwoude", "Zuidhorn", "Zuidlaarderveen",
      "Zuidland", "Zuidlaren", "Zuidoostbeemster", "Zuidschermer", "Zuidveen",
      "Zuidveld", "Zuidvelde", "Zuidwolde Dr", "Zuidwolde Gn", "Zuidzande",
      "Zuilichem", "Zuna", "Zundert", "Zurich", "Zutphen", "Zuurdijk", "Zwaag",
      "Zwaagdijk", "Zwaagwesteinde", "Zwaanshoek", "Zwagerbosch", "Zwammerdam",
      "Zwanenburg", "Zwartebroek", "Zwartemeer", "Zwartewaal", "Zwartsluis",
      "Zweeloo", "Zweins", "Zwiggelte", "Zwijndrecht", "Zwinderen", "Zwolle" };
  private static final int MAX = 5;
  private static final String PLAATSNAAM = "plaatsnaam";

  public PlaatsServlet() {
    super();
  }

  protected void doPost(HttpServletRequest request, HttpServletResponse response)
      throws ServletException, IOException {
    String inp = request.getParameter(PLAATSNAAM);
    ArrayList<String> res = getSteden(inp);
    Gson gson = new Gson();
    String s = gson.toJson(res);
    System.out.println(s);
    response.setContentType(APPLICATION_JSON);
    PrintWriter pw = response.getWriter();
    pw.print(s);
    pw.close();
  }

  private ArrayList<String> getSteden(String term) {
    // zoek eerste voorkomen van term
    ArrayList<String> res = new ArrayList<String>();
    boolean gevonden = false;
    int i = 0;
    int n = steden.length;
    while (i < n && !gevonden) {
      gevonden = steden[i].toUpperCase().startsWith(term);
      if (!gevonden) {
        i++;
      }
    }
    // i geeft index aan of gevonden = false
    int j = 0;
    if (gevonden) {
      while (i < n && j < MAX && steden[i].toUpperCase().startsWith(term)) {
        res.add(steden[i]);
        i++;
        j++;
      }
    }
    return res;
  }

}
